[package]
name = "fuse3"
version = "0.1.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
tokio-runtime = ["tokio"]
async-std-runtime = ["async-std"]
file-lock = []

[dependencies]
futures = "0.3"
byteorder = "1.3"
log = "0.4"
async-trait = "0.1"
libc = "0.2"
bincode = "1.2"
serde = { version = "1.0", features = ["derive"] }

[dependencies.async-std]
version = "1.5"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["fs", "io-util"]
optional = true
