[package]
name = "fuse3"
version = "0.1.0-alpha3"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
categories = ["api-bindings", "filesystem"]
license = "MIT"
repository = "https://github.com/Sherlock-Holo/fuse3"
description = "FUSE user-space library async version implementation."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "examples"]

[features]
tokio-runtime = ["tokio"]
async-std-runtime = ["async-std"]
file-lock = []
unprivileged = ["which"]
doc = ["file-lock", "unprivileged", "async-std-runtime"]

[dependencies]
futures = "0.3"
log = "0.4"
async-trait = "0.1"
libc = "0.2"
bincode = "1.2"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1"
nix = "0.17"
which = { version = "3.1", optional = true }

[dependencies.async-std]
version = "1.5"
features = ["unstable"]
optional = true

[dependencies.tokio]
version = "0.2"
features = ["fs", "io-util", "blocking", "sync", "stream"]
optional = true

[package.metadata.docs.rs]
features = [ "doc" ]